name: Update README with Current Time

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Update timestamp in README
        run: |
          timestamp=$(TZ=Asia/Singapore date '+%a, %d %b %Y at %H:%M:%S +08')
          sed -i "s/Last login: .* from/Last login: $timestamp from/" README.md
          
      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --local user.email "github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add README.md
            git commit -m "Update timestamp in README"
            git push
          fi